---
- name: Simple Playbook #describe the playbook
  hosts: bender

  tasks:
  - name: "apt module -install a simple application"
    apt: #module
      name: figlet # module parameter
      state: absent # module parameter
    become: true #keyword for tasks -- tells ansible how to run this task
